AnimalsParty/AnimalsParty/Models/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnimalsParty.Models
{
    public class City : BaseModel
    {
        public string Name { get; set; }
        public int PostCode { get; set; }

        public int CountryID { get; set; }
        public virtual Country Country { get; set; }

        public virtual List<User> Users { get; set; }
    }
}

AnimalsParty/AnimalsParty/Controllers/CitiesController.cs
using AnimalsParty.Models;
using AnimalsParty.Services.EntityServices;
using AnimalsParty.ViewModels.CitiesVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnimalsParty.Controllers
{
    public class CitiesController : BaseController
    {
        public ActionResult List()
        {
            CitiesService citiesService = new CitiesService();

            CitiesListVM model = new CitiesListVM();
            TryUpdateModel(model);

            model.Cities = citiesService.GetAll();

            if (!String.IsNullOrEmpty(model.Search))
            {
                model.Cities = model.Cities.Where(c => c.Name.ToLower().Contains(model.Search.ToLower())).ToList();
            }

            switch (model.SortOrder)
            {
                case "country_asc":
                    model.Cities = model.Cities.OrderBy(c => c.Country.Name).ToList();
                    break;
                case "country_desc":
                    model.Cities = model.Cities.OrderByDescending(c => c.Country.Name).ToList();
                    break;
                case "postcode_asc":
                    model.Cities = model.Cities.OrderBy(c => c.PostCode).ToList();
                    break;
                case "postcode_desc":
                    model.Cities = model.Cities.OrderByDescending(c => c.PostCode).ToList();
                    break;
                case "name_desc":
                    model.Cities = model.Cities.OrderByDescending(c => c.Name).ToList();
                    break;
                case "name_asc":
                default:
                    model.Cities = model.Cities.OrderBy(c => c.Name).ToList();
                    break;
            }

            return View(model);
        }

        public ActionResult Edit(int? id)
        {
            CitiesService citiesService = new CitiesService();

            CitiesEditVM model = new CitiesEditVM();
            City city;

            if (!id.HasValue)
            {
                city = new City();
            }
            else
            {
                city = citiesService.GetByID(id.Value);
                if (city == null)
                {
                    return RedirectToAction("List");
                }
            }

            model.ID = city.ID;
            model.Name = city.Name;
            model.PostCode = city.PostCode;
            model.CountryID = city.CountryID;

            //model.Countries = new CountriesRepository().GetAll(); 1
            //model.Countries = new SelectList(new CountriesRepository().GetAll(), "ID", "Name"); //2 
            model.Countries = citiesService.GetSelectedCountries(); // 3

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit()
        {
            CitiesService citiesService = new CitiesService();

            CitiesEditVM model = new CitiesEditVM();
            TryUpdateModel(model);

            if (!ModelState.IsValid)
            {
                model.Countries = citiesService.GetSelectedCountries();
                return View(model);
            }

            City city;
            if (model.ID == 0)
            {
                city = new City();
            }
            else
            {
                city = citiesService.GetByID(model.ID);
                if (city == null)
                {
                    return RedirectToAction("List");
                }
            }

            city.ID = model.ID;
            city.Name = model.Name;
            city.PostCode = model.PostCode;
            city.CountryID = model.CountryID;

            citiesService.Save(city);

            return RedirectToAction("List");
        }

        public ActionResult Delete(int? id)
        {
            CitiesService citiesService = new CitiesService();

            if (!id.HasValue)
            {
                return RedirectToAction("List");
            }

            citiesService.Delete(id.Value);

            return RedirectToAction("List");
        }
    }
}

AnimalsParty/AnimalsParty/Views/Cities/Edit.cshtml
@model AnimalsParty.ViewModels.CitiesVM.CitiesEditVM

@{
    ViewBag.Title = Model.ID > 0 ? "Edit City" : "Create City";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DropDownListFor(model => model.CountryID, new SelectList(Model.Countries, "ID", "Name"), new { @class = "form-control" })*@
                @Html.DropDownListFor(model => model.CountryID, Model.Countries, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

AnimalsParty/AnimalsParty/Views/Cities/List.cshtml
@model AnimalsParty.ViewModels.CitiesVM.CitiesListVM

@{
    ViewBag.Title = "List Cities";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Create New", "Edit")
</p>

@using (Html.BeginForm("List", "Cities", FormMethod.Get))
{
    <div>
        Find by name: @Html.TextBoxFor(model => model.Search, new { @class = "form-control" })
        <input type="submit" value="Search" class="btn btn-primary" />
    </div>
}

@if (Model.Cities.Count == 0)
{
    <div class="alert alert-info">No Cities Found</div>
}
else
{
    <table class="table table-hover table-striped table-bordered">
        <tr>
            <th>
                @{
                    @Html.ActionLink("Name", "List", "Cities", new RouteValueDictionary { { "SortOrder", Model.SortOrder == "name_desc" ? "name_asc" : "name_desc" }, { "Search", Model.Search } }, null)
                }
            </th>
            <th>
                @{
                    @Html.ActionLink("Post Code", "List", "Cities", new RouteValueDictionary { { "SortOrder", Model.SortOrder == "postcode_desc" ? "postcode_asc" : "postcode_desc" }, { "Search", Model.Search } }, null)
                }
            </th>
            <th>
                @{
                    @Html.ActionLink("Country", "List", "Cities", new RouteValueDictionary { { "SortOrder", Model.SortOrder == "country_desc" ? "country_asc" : "country_desc" }, { "Search", Model.Search } }, null)
                }
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Cities)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    <a href="#" data-toggle="modal" data-target="#modal-delete-confirmation" data-url="/Cities/Delete/@item.ID" data-additionalinfo="@item.Name">
                        Delete
                    </a>
                </td>
            </tr>
        }

    </table>
}

@section FooterSection {
    @Html.Partial("~/Views/Shared/PartialViews/_DeleteConfirmation.cshtml")
}